### ISSUE TITLE
SAFE DOM network connection state change is never called

### ISSUE THREAD

**Issue by happybeing** [maidsafe/beaker-plugin-safe-app#123]
Using: Peruse built locally for mock (0.41 I think)

I pass a callback to `safeApp.initialise()` but this is never called, so my app thinks the network is always disconnected. I beleive the callback should be called when I do a successful `safeApp.connectAuthorised()`.

Here's my code:

https://github.com/theWebalyst/solid-safenetwork/blob/wip/src/safenetwork-webapi.js#L220

**Comment by hunterlester** [comment]
@theWebalyst The documentation there is misleading. This function sets a fixed callback which updates the client state when the network state changes.
https://github.com/joshuef/peruse/blob/master/app/extensions/safe/api/app.js#L117

I'll send a PR now to update docs. Thank you.

**Comment by happybeing** [comment]
I'm not sure how this relates to the callback never being called?

**Comment by hunterlester** [comment]
I was mistaken. I was meaning to say that the function doesn't take a custom callback, which was wrong. It does take a custom callback but however is only implemented for this repository and not in Peruse.

This plugin isn't being used for Peruse.

**Comment by bochaco** [comment]
Some aspects to consider here, this won't work with mock, the network state change callback would therefore be invoked only when it's disconnected from a live network (I don't think it's possible to mimic a disconnection from the mock at the moment). 
Apart from that, the re-connection flow is not working in Peruse (this is a known issue), therefore Peruse doesn't invoke the `reconnect` function which is the one that will not only try to reconnect to the network but also send the "connected" state change if successful.
I would file a bug in Peruse repository instead if there is no issue in the Beaker safe_app plugin with the re-connection and/or network state change (I believe there isn't).

FYI, I just created this task to implement some mechanism for testing network state change with mock routing: https://maidsafe.atlassian.net/browse/MAID-2563

**Comment by happybeing** [comment]
I think there may still be a larger issue not necessarily just in Peruse, because I would expect this callback to be called at least once - as implied by the documentation - when the connection is established (eg by connectAuthorised()). Either way, the circumstances could be clarified.

**Comment by bochaco** [comment]
In that case the safe_app native lib doesn't invoke the callback (it may have been the case before, I don't remember exactly), in fact it does it only when it gets disconnected, at the safe_app_nodejs we invoke the callback in the re-connection flow (not the native lib). Thus we could consider invoking the callback also from safe_app_nodejs when connecting for the first time.

**Comment by happybeing** [comment]
> Thus we could consider invoking the callback also from safe_app_nodejs when connecting for the first time

This seems sensible and is what I expected based on the documentation. If not, I think it would help if the example showed how the application should handle the init of a local `isConnected` state variable.

**Comment by bochaco** [comment]
Thanks @theWebalyst for bringing all this to our attention. I just created this other task to work on this in safe_app_nodejs package: https://maidsafe.atlassian.net/browse/MAID-2564

**Comment by bochaco** [comment]
This is now implemented in safe-app-nodejs v0.9.0, and in Peruse v0.7.0
