### ISSUE TITLE
Error when calling window.safeCrypto.generateNonce(): Invalid handle: undefined

### ISSUE THREAD

**Issue by birkeal** [maidsafe/beaker-plugin-safe-app#52]
I just wanted to play around with Private MDs and noticed that I can't generate a nonce. I first authenticate against the network and afterwards I call window.safeCrypto.generateNonce() which fails with the following msg. It can be tested here: safe://www.lol/index.html
First click auth button, wait, and afterwards click create private MD.

Promise {[[PromiseStatus]]: "pending", [[PromiseValue]]: undefined}__proto__: Promise[[PromiseStatus]]: "rejected"[[PromiseValue]]: Error: Invalid handle: undefined
    at onCbReply (F:\safe\safe-browser\resources\app\node_modules\pauls-electron-rpc\lib\import-api.js:203:19)
    at EventEmitter.onIPCMessage (F:\safe\safe-browser\resources\app\node_modules\pauls-electron-rpc\lib\import-api.js:118:14)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)message: "Invalid handle: undefined"stack: (...)get stack: stack()set stack: stack()__proto__: Object
F:\safe\safe-browser\resources\app\node_modules\pauls-el…:203

Uncaught (in promise) Error: Invalid handle: undefined(…)onCbReply @ F:\safe\safe-browser\resources\app\node_modules\pauls-el…:203onIPCMessage @ F:\safe\safe-browser\resources\app\node_modules\pauls-el…:118emitMany @ events.js:127emit @ events.js:201

**Comment by bochaco** [comment]
Hi @Mindphreaker , you are missing the parameter for the function, the error `Error: Invalid handle: undefined` means that it's expecting a handle and it is undefined. Please try by passing the app handle.

**Comment by birkeal** [comment]
@bochaco ah thanks! I was mislead by the documentation, because in the newPrivate example it's missing too: http://docs.maidsafe.net/beaker-plugin-safe-app/#windowsafemutabledatanewprivate
Maybe this can be fixed to prevent confusion. :)

window.safeCrypto.generateNonce() <- MISSING PARAMETER!!! ;)
   .then((nonce) => window.safeMutableData.newPrivate(appHandle, name, 15001, secKey, nonce))
   .then((mdHandle) => window.safeMutableData.getNameAndTag(mdHandle))
   .then((r) => console.log('New Private MutableData created with tag: ', r.tag, ' and name: ', r.name.buffer));

**Comment by bochaco** [comment]
great!, definitely, we can use this ticket to solve that issue in the examples then. Thanks @Mindphreaker .

**Comment by bochaco** [comment]
This is being fixed with PR #54
